AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 3

Resources:
  NickNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: nickname.handler
      Runtime: python3.8
      Events:
        NickName:
          Type: Api
          Properties:
            Path: /nickname
            Method: post
        NickNameAgain:
          Type: Api
          Properties:
            Path: /nickname-again
            Method: post

Outputs:
  NickNameApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/nick/"
